name: ovro_data_recorder_doc_env

channels:
  - conda-forge

dependencies:
  - numpy
  - python
  - scipy
  - sphinx
  - astropy
  - python-casacore
  - pip
  - h5py
  - matplotlib
  - pip:
    - etcd3
    - "git+https://github.com/dsa110/dsa110-pyutils"
    - "git+https://github.com/ovro-lwa/mnc_python"
    - "git+https://github.com/ovro-lwa/lwa-antpos"
