version: 2

build:
  apt_packages:
    - autoconf
    - exuberant-ctags
    - gawk
    - gfortran
    - grep
    - g++
    - libtool
    - make

conda:
  environment: .environment_doc.yml

python:
  install:
    - method: pip
    - path: .
