version: 2

build:
  apt_packages:
    - gfortran
  jobs:
    pre_build:
      git clone https://github.com/leda-telescope/bifrost
      cd bifrost/python
      make
      pip install .
      cd ../..

conda:
  environment: .environment_doc.yml
