version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.8"
  apt_packages:
    - gfortran
  jobs:
    pre_build:
      - git clone https://github.com/leda-telescope/bifrost
      - cd bifrost/python
      - make
      - pip install .
      - cd ../..

conda:
  environment: .environment_doc.yml
