version: 2

build:
  os: ubuntu-22.04
  apt_packages:
    - autoconf
    - exuberant-ctags
    - gawk
    - gfortran
    - grep
    - g++
    - libtool
    - make
    - rsyslog
  tools:
    python: "mambaforge-22.9"
  jobs:
    post_checkout:
      - git submodule init
      - git submodule update
    post_create_environment:
      - bash ./docs/.rtd_bifrost_helper.sh
  
conda:
  environment: docs/.rtd_environment.yaml

python:
  install:
    - method: pip
      path: .

sphinx:
  configuration: docs/source/conf.py
