name: ovro_data_recorder_doc_env

channels:
  - conda-forge

dependencies:
  - numpy
  - python
  - scipy
  - sphinx
  - astropy
  - python-casacore
  - pip
  - h5py
  - matplotlib
  - ctypesgen
  - setuptools-scm
  - pyzmq
