name: ovro_data_recorder_doc_env

channels:
  - conda-forge

dependencies:
  - numpy
  - python
  - scipy
  - sphinx
  - astropy
  - python-casacore
  - pip
  - h5py
  - matplotlib
  - ctypesgen
  - setuptools_scm
  - pip:
    - etcd3
    - "git+https://github.com/dsa110/dsa110-pyutils"
    - "git+https://github.com/ovro-lwa/mnc_python"
    - "git+https://github.com/ovro-lwa/lwa-antpos@0.6.10"
    - pint
    - "git+https://github.com/ledatelescope/bifrost@pip-bootstrap#subdirectory=python"
